package-lock.json, package.json
Resolved npm install issue in my directory by updating:
"babel-eslint": "^8.2.6"
=> updated dev dependencies babel-eslint

client/components/UI/AppBar.js, client/components/allProducts.js, client/components/home.js, client/components/navbar.js
=> fix navbar

client/components/UI/AppBar.js, client/components/navbar.js, client/components/singleProduct.js
=> single component working but ugly

client/components/UI/AppBar.js, client/components/allProducts.js, client/components/navbar.js, client/store/allProduct.js
=> fixed the front-end issue of AllProduct

adminMiddleware.js, client/components/UI/AppBar.js, client/components/auth-form.js, package.json, server/db/models/user.js
=> modify navbar, install prop-types and add adminMiddleware

client/components/allProducts.js, client/components/singleProduct.js, client/routes.js, public/style.css
=> Allproducts frontend progress with mui

client/components/singleProduct.js, public/style.css
=> single product updated with style

client/components/singleProduct.js
=> clean files

client/components/allProducts.js, client/components/singleProduct.js, public/style.css
=> corrected merge issues

package.json, public/index.html
=> moved script file in index.html

client/components/singleProduct.js, public/style.css, server/db/models/index.js, server/db/models/order.js
=> Added styling for Single page, and created Model for order table

client/components/UI/AppBar.js, server/api/index.js, server/api/orders.js, server/db/models/index.js, server/db/models/orderItem.js
=> finalize order model & create orders route

client/components/singleProduct.js, public/style.css
=> Single product stlye

client/components/allProducts.js, public/style.css
=> allproduct element linked to singleProd view and added cart icon

client/components/Cart.js, client/components/singleProduct.js, client/routes.js, package.json
=> add cart component and install mui/system

client/components/home/featuredExperiences.js, client/components/home/featuredInstructors.js, client/components/home/index.js, client/components/home/introduction.js, client/components/home/testimonials.js, public/index.html, public/style.css
=> Home component

client/components/home/featuredExperiences.js
=> fixed local issue of featured Experiences

server/api/index.js
=> fixing route error

client/components/UI/AppBar.js, client/components/singleProduct.js, client/store/index.js, client/store/orderItems.js, client/store/userOrderItems.js, server/api/orderItems.js
=> added front end route to addToCart from singleProduct view

client/components/admin/AllUsers.js, client/routes.js, client/store/user.js, script/seed.js, server/api/users.js, server/index.js
=> passport implementation

README.md, client/components/UI/AppBar.js, client/components/cart/guestCart.js, client/components/cart/index.js, client/store/orders.js, client/store/userCart.js, server/api/orders.js
=> final fixes to the cart

client/components/UI/AppBar.js
=> Appbar badge
